name = "Aero Explorers"
author = "kodiitulip"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fab4e8b2e5585a70a5a73bf6724443c20e351ff870683af4fbf51f991401a5c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
