name = "Aero Explorers"
author = "kodiitulip"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75279d0ba99d0e8c41863c589d4b2982c9b3d3796527580e13c75592056c8c0c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
