#.
# Default: 2
# Range: > 1
sBend_targetT = 6
#.
# Default: 2
# Range: > 1
slope_turnSize = 6
#.
#Horizontal blocks per vertical block
# Default: 3
# Range: > 1
straightAscend_minHDistance = 8
#.
# Default: 7
# Range: > 1
turn_minTurnSize = 7
